### ISSUE TITLE
Bet status completion 

### ISSUE THREAD

**Issue by Amzani** [shapeitapp/shapeitapp#23]
We could use this concept on the Bet cards

<img width="935" alt="Screenshot 2023-07-07 at 18 28 17" src="https://github.com/shapeitapp/shapeitapp/assets/554438/568e62ee-7999-467c-baa3-d1aa6515a9e7">

<img width="1378" alt="Screenshot 2023-07-07 at 18 28 53" src="https://github.com/shapeitapp/shapeitapp/assets/554438/38784dc0-73b4-4b57-b1a3-fa58706ef003">

### Colors

From `bg-green-800` to `bg-green-200`
https://tailwindcss.com/docs/background-color

**Comment by Amzani** [comment]
/progress 20 

I've done a CodePen implementation here: https://codepen.io/samz90/pen/OJaxqMa

**Comment by koukama** [comment]
@Amzani @fmvilas 

I choose to make a simple progress bar, I find more simple and user friendly.  wich one do you prefer ?

### Option A 

<img width="1421" alt="Screenshot 2023-07-18 at 21 13 12" src="https://github.com/shapeitapp/shapeitapp/assets/23728202/cb168823-cd18-499c-b094-f3d93dae33ea">

### Option B

<img width="1436" alt="Screenshot 2023-07-18 at 15 42 13" src="https://github.com/shapeitapp/shapeitapp/assets/23728202/c15e2a83-5793-450e-a595-5e66c20264a4">

**Comment by Amzani** [comment]
I vote for Option B)

**Comment by fmvilas** [comment]
Both look good to me 👍 It would be cool that aside from the length of the progress bar, the color could change too. For instance, if progress is less than 50% the progress bar would be red, if it's less than 80% it's yellow, and if it's above 80%, it's green.

But this could be done on a separate PR. Either option A or B are already providing value so I'd merge it as soon as possible and iterate on it.

**Comment by koukama** [comment]
Thanks for your feedback @fmvilas I'll create a new issue for it
