### ISSUE TITLE
Show remaining weeks

### ISSUE THREAD

**Issue by fmvilas** [shapeitapp/shapeitapp#32]
It would be cool to show the remaining weeks or a calendar on hover here:

<img width="668" alt="Captura de pantalla 2023-07-06 a las 11 59 27" src="https://github.com/shapeitapp/shapeitapp/assets/242119/9a4889b5-7729-496d-a7b7-f4d779dda327">

I always end up having to calculate them by hand 😄

**Comment by Amzani** [comment]
👍 for showing remaining weeks as a tooltip (See example from JIRA).

We could then move also the text bellow "The current cycle started on ...." to simplify the UI.

Then we could have in the tooltip when you hover over `XX DAYS REMAINING` something like:

```
3 Weeks remaining
Start(ed) on 19/Jun/23
Finish(ed) on 31/Jul/23
```

If number of days are indivisible by 7 then we show also remaining number of days, `e.g 24 days remaining -> 3 Weeks and 3 days remaining` 

<img width="318" alt="Screenshot 2023-07-07 at 11 06 18" src="https://github.com/shapeitapp/shapeitapp/assets/554438/4627848d-287f-4f83-94dd-01c057122768">

**Comment by fmvilas** [comment]
Yup. I love it 👍
