### ISSUE TITLE
Setup GitHub App

### ISSUE THREAD

**Issue by fmvilas** [shapeitapp/shapeitapp#34]
Related to #27

**Comment by Amzani** [comment]
/progress 10

Found a framework that can help: https://probot.github.io/docs/development/

**Comment by Amzani** [comment]
/progress 90

A working app that comment pitch issues https://github.com/shapeitapp/shapeit-github-app

**Comment by Amzani** [comment]
/progress 95 

Trying out render.com for deployment

**Comment by Amzani** [comment]
/progress 100

Done

**Comment by Amzani** [comment]
/progress 90

Bootstrapped the initial app, however we still need to find a solution for hosting as for now the code is deployed in my private server.

**Comment by Amzani** [comment]
/progress 90

Bootstrapped the initial app, however we still need to find a solution for hosting as for now the code is deployed in my private server.

**Comment by Amzani** [comment]
/progress 100 

Bootstrapped the initial app and [deployed the app in fly.io](https://github.com/shapeitapp/shapeit-github-app/pull/20)
