### ISSUE TITLE
[PITCH]: See previous cycles

### ISSUE THREAD

**Issue by Amzani** [shapeitapp/shapeitapp#38]
### Problem

I want to see previous cycles.
Currently it's not possible.

<img width="1143" alt="Screenshot 2023-07-10 at 10 03 58" src="https://github.com/shapeitapp/shapeitapp/assets/554438/357b5967-1efc-44cb-b549-0aabbffe02a6">

### Solution

Use the arrows to navigate in the past cycles.

<img width="1193" alt="Screenshot 2023-07-10 at 10 05 45" src="https://github.com/shapeitapp/shapeitapp/assets/554438/1ffbde7b-d4f9-4a14-bdff-f66f1a7dd619">

### Rabbit holes

Not identified for now

### Scope

- [ ] Implementation

**Comment by fmvilas** [comment]
This looks like a bug. It was there before.

**Comment by Amzani** [comment]
Can't reproduce see https://shapeit.app/projects/org/shapeitapp/1/cycles/e6e76687?issue=I_kwDOJtUObM5qpS_D
In https://shapeit.app/projects/org/asyncapi/27/cycles/0303de9c we can't go back to cycle 1 as all bets have changes to cycle 2, I think we will soon need a DB to store this information, as we accept that bets can be done in multiple cycles.
