### ISSUE TITLE
Application gives an error when the user has no GH projects created

### ISSUE THREAD

**Issue by smoya** [shapeitapp/shapeitapp#40]
![Google Chrome_Phcio07r](https://github.com/shapeitapp/shapeitapp/assets/1083296/dbddd1c2-7040-4277-8b02-a32971ce4975)

The error message logged into the dev console says:

```
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
window.console.error @ 488-881aff3ca3fb2fa9.js:1
```

**Comment by smoya** [comment]
The reality is that after creating a project, It is still not working to me.

**Comment by fmvilas** [comment]
Is this still happening for you, Sergio? 🤔 I wonder what this could be.

**Comment by smoya** [comment]
> Is this still happening for you, Sergio? 🤔 I wonder what this could be.

Still happening. I tried revoking permissions so GH ask again but still happening. 
My GH user is part of several teams/groups/companies I don't know how GH call it atm. Just in case you do some logic based on that?
Don't you have any kind of logs or a way to enable logs to console in prod?

**Comment by smoya** [comment]
I ran the app locally (All config filled except `NEXTAUTH_SECRET` that I left the default). 

The error that it showed me:

![Google Chrome_MgO02dP3](https://github.com/shapeitapp/shapeitapp/assets/1083296/e2bca0cd-3db1-466e-8a99-48cd15ead20b)

In the logs, I see some forbidden stuff which is expected since those orgs don't allow to access data. 

Full logs can be found [here](https://gist.github.com/smoya/4a31af59a18ca0a634cc7ca367814f06).

**Comment by smoya** [comment]
Ok, I can confirm the issue is with the org repos.

All those `orgProjects` from https://github.com/shapeitapp/shapeitapp/blob/main/src/app/projects/page.js#L117-L124 don't come (in my case, and I guess because permissions) with the `creator` field required in the `ProjectCard.js` https://github.com/shapeitapp/shapeitapp/blob/main/src/components/ProjectCard.js#L42

Maybe you should filter in the GraphQL query for those with permission if possible?
