### ISSUE TITLE
Flag a scope as "at risk"

### ISSUE THREAD

**Issue by fmvilas** [shapeitapp/shapeitapp#41]
It would be cool to have a slash command (similar to `/progress`) to flag an issue as "at risk". It could be something like:

```
/at-risk [Optional message explaining why it's at risk.]
```

Similarly, once #25 is implemented, we could place a button in the comment that would let you mark it as a "at-risk". Also, the UI could show some indicator and a button to do the same thing, which in turn, will update the comment mentioned before.

Example: https://github.com/asyncapi/studio/issues/684#issuecomment-1624075096. It would have been useful there.

Related to #27

**Comment by Amzani** [comment]
/progress 10

Started to look at it

**Comment by Amzani** [comment]
/progress 80

In review
